packages:
    - 'packages/*'
catalog:
    vitest: https://pkg.pr.new/vitest@5df7414
    '@vitest/browser': https://pkg.pr.new/@vitest/browser@5df7414
    '@vitest/ui': https://pkg.pr.new/@vitest/ui@5df7414
    firebase: 11.0.1
    es-toolkit: 1.25.2
