packages:
    - 'packages/*'
catalog:
    vitest: https://pkg.pr.new/vitest@4ec301b
    '@vitest/browser': https://pkg.pr.new/@vitest/browser@4ec301b
    '@vitest/spy': https://pkg.pr.new/@vitest/spy@4ec301b
    '@vitest/ui': https://pkg.pr.new/@vitest/ui@4ec301b
    firebase: 10.14.1
    es-toolkit: 1.24.0
