packages:
    - 'packages/*'
catalog:
    typescript: 5.8.3
    knip: 5.61.0
    eslint: 9.29.0
    vitest: 3.2.3
    '@vitest/browser': 3.2.3
    '@vitest/ui': 3.2.3
    '@vitest/coverage-v8': 3.2.3
    firebase: 11.9.1
    es-toolkit: 1.39.3
    '@posva/event-emitter': 1.0.3
