packages:
    - 'packages/*'
catalog:
    vitest: 3.2.2
    '@vitest/browser': 3.2.2
    '@vitest/ui': 3.2.2
    '@vitest/coverage-v8': 3.2.2
    firebase: 11.9.0
    es-toolkit: 1.39.0
    '@posva/event-emitter': 1.0.2
