packages:
    - 'packages/*'
catalog:
    vitest: 3.1.2
    '@vitest/browser': 3.1.2
    '@vitest/ui': 3.1.2
    '@vitest/coverage-v8': 3.1.2
    firebase: 11.6.1
    es-toolkit: 1.36.0
    '@posva/event-emitter': 1.0.2
