packages:
    - 'packages/*'
catalog:
    vitest: https://pkg.pr.new/vitest@d262e05
    '@vitest/browser': https://pkg.pr.new/@vitest/browser@d262e05
    '@vitest/ui': https://pkg.pr.new/@vitest/ui@d262e05
    '@vitest/coverage-v8': https://pkg.pr.new/@vitest/coverage-v8@d262e05
    firebase: 11.1.0
    es-toolkit: 1.31.0
    '@posva/event-emitter': 1.0.2
