packages:
    - 'packages/*'
catalog:
    vitest: https://pkg.pr.new/vitest@6a09cc3
    '@vitest/browser': https://pkg.pr.new/@vitest/browser@6a09cc3
    '@vitest/ui': https://pkg.pr.new/@vitest/ui@6a09cc3
    '@vitest/coverage-v8': https://pkg.pr.new/@vitest/coverage-v8@6a09cc3
    firebase: 11.1.0
    es-toolkit: 1.31.0
    '@posva/event-emitter': 1.0.2
