packages:
    - 'packages/*'
catalog:
    vitest: https://pkg.pr.new/vitest@da6d2ea
    '@vitest/browser': https://pkg.pr.new/@vitest/browser@da6d2ea
    '@vitest/spy': https://pkg.pr.new/@vitest/spy@da6d2ea
    '@vitest/ui': https://pkg.pr.new/@vitest/ui@da6d2ea
    firebase: 10.14.1
    es-toolkit: 1.25.1
