packages:
    - 'packages/*'
catalog:
    vitest: https://pkg.pr.new/vitest@3a8b56b
    '@vitest/browser': https://pkg.pr.new/@vitest/browser@3a8b56b
    '@vitest/ui': https://pkg.pr.new/@vitest/ui@3a8b56b
    firebase: 11.0.1
    es-toolkit: 1.25.2
