packages:
    - 'packages/*'
catalog:
    vitest: 3.2.0-beta.1
    '@vitest/browser': 3.2.0-beta.1
    '@vitest/ui': 3.2.0-beta.1
    '@vitest/coverage-v8': 3.2.0-beta.1
    firebase: 11.7.3
    es-toolkit: 1.37.2
    '@posva/event-emitter': 1.0.2
