packages:
    - 'packages/*'
catalog:
    vitest: 3.2.0-beta.3
    '@vitest/browser': 3.2.0-beta.3
    '@vitest/ui': 3.2.0-beta.3
    '@vitest/coverage-v8': 3.2.0-beta.3
    firebase: 11.8.1
    es-toolkit: 1.38.0
    '@posva/event-emitter': 1.0.2
