packages:
    - 'packages/*'
catalog:
    vitest: https://pkg.pr.new/vitest@9edfa19
    '@vitest/browser': https://pkg.pr.new/@vitest/browser@9edfa19
    '@vitest/spy': https://pkg.pr.new/@vitest/spy@9edfa19
    '@vitest/ui': https://pkg.pr.new/@vitest/ui@9edfa19
    firebase: 10.14.0
    es-toolkit: 1.23.0
