packages:
    - 'packages/*'
catalog:
    vitest: https://pkg.pr.new/vitest@2fb585a
    '@vitest/browser': https://pkg.pr.new/@vitest/browser@2fb585a
    '@vitest/ui': https://pkg.pr.new/@vitest/ui@2fb585a
    '@vitest/coverage-v8': https://pkg.pr.new/@vitest/coverage-v8@2fb585a
    firebase: 11.0.2
    es-toolkit: 1.29.0
    '@posva/event-emitter': 1.0.2
