packages:
    - 'packages/*'
catalog:
    vitest: 3.0.9
    '@vitest/browser': 3.0.9
    '@vitest/ui': 3.0.9
    '@vitest/coverage-v8': 3.0.9
    firebase: 11.5.0
    es-toolkit: 1.33.0
    '@posva/event-emitter': 1.0.2
