packages:
    - 'packages/*'
catalog:
    vitest: https://pkg.pr.new/vitest@b82584c
    '@vitest/browser': https://pkg.pr.new/@vitest/browser@b82584c
    '@vitest/spy': https://pkg.pr.new/@vitest/spy@b82584c
    '@vitest/ui': https://pkg.pr.new/@vitest/ui@b82584c
    firebase: 11.0.0
    es-toolkit: 1.25.2
