packages:
    - 'packages/*'
catalog:
    vitest: https://pkg.pr.new/vitest@e89c369
    '@vitest/browser': https://pkg.pr.new/@vitest/browser@e89c369
    '@vitest/ui': https://pkg.pr.new/@vitest/ui@e89c369
    '@vitest/coverage-v8': https://pkg.pr.new/@vitest/coverage-v8@e89c369
    firebase: 11.1.0
    es-toolkit: 1.31.0
    '@posva/event-emitter': 1.0.2
