packages:
    - 'packages/*'
catalog:
    vitest: https://pkg.pr.new/vitest@61b3016
    '@vitest/browser': https://pkg.pr.new/@vitest/browser@61b3016
    '@vitest/ui': https://pkg.pr.new/@vitest/ui@61b3016
    '@vitest/coverage-v8': https://pkg.pr.new/@vitest/coverage-v8@61b3016
    firebase: 11.1.0
    es-toolkit: 1.30.1
    '@posva/event-emitter': 1.0.2
