packages:
    - 'packages/*'
catalog:
    vitest: https://pkg.pr.new/vitest@537fa5e
    '@vitest/browser': https://pkg.pr.new/@vitest/browser@537fa5e
    '@vitest/ui': https://pkg.pr.new/@vitest/ui@537fa5e
    '@vitest/coverage-v8': https://pkg.pr.new/@vitest/coverage-v8@537fa5e
    firebase: 11.2.0
    es-toolkit: 1.31.0
    '@posva/event-emitter': 1.0.2
