packages:
    - 'packages/*'
catalog:
    vitest: https://pkg.pr.new/vitest@bfea79f
    '@vitest/browser': https://pkg.pr.new/@vitest/browser@bfea79f
    '@vitest/ui': https://pkg.pr.new/@vitest/ui@bfea79f
    '@vitest/coverage-v8': https://pkg.pr.new/@vitest/coverage-v8@bfea79f
    firebase: 11.1.0
    es-toolkit: 1.31.0
    '@posva/event-emitter': 1.0.2
