export enum InventoryItemType {
    DRINK = "drink",
    // Retail products (e.g., tobacco, merchandise)
    RETAIL = "retail",
}

interface BaseInventoryItem {
    /**
     * Unique identifier for the inventory item
     * Generated by the database
     */
    id: string;

    /**
     * The full name of the product
     * Example: "Jack Daniel's Old No. 7", "Coca-Cola 330ml"
     */
    name: string;

    /**
     * The primary classification of the item
     * Used to distinguish between drinks, consumables, equipment, and retail items
     */
    type: InventoryItemType;

    /**
     * Current quantity in stock
     * Represents the number of units currently available
     */
    quantity: number;

    /**
     * Specific style or variant of the product
     * Provides additional classification detail
     * Example: "Irish Whiskey", "London Dry Gin", "Cola"
     */
    style?: string | undefined;

    /**
     * Geographic origin of the product
     * Used for classification and sourcing
     * Example: "Scotland", "France", "Japan"
     */
    region?: string | undefined;

    /**
     * Commercial brand name of the product
     * Example: "Absolut", "Heineken", "Red Bull"
     */
    brand?: string | undefined;

    /**
     * Name or identifier of the supplier
     * Used for reordering and supplier management
     */
    supplier?: string;

    /**
     * Indicates if the item is currently available for use
     * Can be used to temporarily disable items without deletion
     */
    isActive?: boolean;

    /**
     * Date of the last inventory restock
     * ISO string format
     * Used for inventory turnover analysis
     */
    lastRestockDate?: string;

    /**
     * Volume of the container in milliliters
     * Example: 750 for a standard wine bottle
     */
    volume?: number | undefined;

    /**
     * Detailed description of the product
     * Can include tasting notes, serving suggestions, etc.
     */
    description?: string | undefined;

    /**
     * Additional properties for special cases
     * Allows for flexible extension without schema changes
     * Example: { "allergens": ["sulfites"], "vintage": "2018" }
     */
    customProperties?: Record<string, any>;
}

export interface DrinkItem extends BaseInventoryItem {
    type: InventoryItemType.DRINK;
    mainCategory: DrinkMainCategory;
    subCategory: DrinkSubCategory;
    alcoholContent?: number;
}

type DrinkSubCategory = {
    [DrinkMainCategory.SPIRITS]: SpiritSubCategory;
    [DrinkMainCategory.WINE]: WineSubCategory;
    [DrinkMainCategory.BEER]: BeerSubCategory;
    [DrinkMainCategory.NON_ALCOHOLIC]: NonAlcoholicCategory;
    [DrinkMainCategory.COCKTAIL_COMPONENTS]: CocktailComponentCategory;
}[DrinkMainCategory];

export interface RetailItem extends BaseInventoryItem {
    type: InventoryItemType.RETAIL;
    mainCategory: RetailMainCategory;
    subCategory: RetailSubCategory;
}

type RetailSubCategory = {
    [RetailMainCategory.TOBACCO]: TobaccoSubCategory;
}[RetailMainCategory];

export type InventoryItemDoc = DrinkItem | RetailItem;

export enum RetailMainCategory {
    TOBACCO = "tobacco",
}

export enum TobaccoSubCategory {
    CIGARETTES = "cigarettes",
}

export enum DrinkMainCategory {
    SPIRITS = "spirits",
    WINE = "wine",
    BEER = "beer",
    NON_ALCOHOLIC = "non-alcoholic",
    COCKTAIL_COMPONENTS = "cocktail-components",
}

export enum SpiritSubCategory {
    VODKA = "vodka",
    WHISKEY = "whiskey",
    GIN = "gin",
    RUM = "rum",
    TEQUILA = "tequila",
    COGNAC = "cognac",
    BRANDY = "brandy",
    LIQUEUR = "liqueur",
}

export enum WineSubCategory {
    RED = "red",
    WHITE = "white",
    ROSE = "rose",
    SPARKLING = "sparkling",
    FORTIFIED = "fortified",
}

export enum BeerSubCategory {
    LAGER = "lager",
    ALE = "ale",
    STOUT = "stout",
    CRAFT = "craft",
    // For region-specific beers
    LOCAL = "local",
    IMPORTED = "imported",
}

export enum NonAlcoholicCategory {
    SOFT_DRINK = "soft-drink",
    ENERGY_DRINK = "energy-drink",
    WATER = "water",
    JUICE = "juice",
    COFFEE = "coffee",
    TEA = "tea",
    MOCKTAIL = "mocktail",
}

export enum CocktailComponentCategory {
    MIXER = "mixer",
    SYRUP = "syrup",
    BITTER = "bitter",
    GARNISH = "garnish",
    ICE = "ice",
}

export type CreateInventoryItemPayload = Omit<InventoryItemDoc, "id">;

export function isDrinkItem(item: Pick<InventoryItemDoc, "type">): item is DrinkItem {
    return item.type === InventoryItemType.DRINK;
}

export function isRetailItem(item: Pick<InventoryItemDoc, "type">): item is RetailItem {
    return item.type === InventoryItemType.RETAIL;
}
