import { LocalStorage } from "quasar";

export const myIcons: Record<string, string> = {
    "arrow-expand": "svguse:/svg-icons/ft-icons.svg#arrow-expand",
    "arrow-sort-down": "svguse:/svg-icons/ft-icons.svg#arrow-sort-down",
    "arrow-sort-up": "svguse:/svg-icons/ft-icons.svg#arrow-sort-up",
    arrow_drop_down: "svguse:/svg-icons/ft-icons.svg#chevron-down",
    "at-symbol": "svguse:/svg-icons/ft-icons.svg#at-symbol",
    bookmark: "svguse:/svg-icons/ft-icons.svg#bookmark",
    bug: "svguse:/svg-icons/ft-icons.svg#bug",
    calendar: "svguse:/svg-icons/ft-icons.svg#calendar",
    camera: "svguse:/svg-icons/ft-icons.svg#camera",
    check: "svguse:/svg-icons/ft-icons.svg#check",
    chevron_double_right: "svguse:/svg-icons/ft-icons.svg#chevron-double-right",
    chevron_down: "svguse:/svg-icons/ft-icons.svg#chevron-down",
    chevron_left: "svguse:/svg-icons/ft-icons.svg#chevron-left",
    chevron_right: "svguse:/svg-icons/ft-icons.svg#chevron-right",
    chevron_up: "svguse:/svg-icons/ft-icons.svg#chevron-up",
    clock: "svguse:/svg-icons/ft-icons.svg#clock",
    close: "svguse:/svg-icons/ft-icons.svg#close",
    "cog-wheel": "svguse:/svg-icons/ft-icons.svg#cog-wheel",
    "color-picker": "svguse:/svg-icons/ft-icons.svg#color-picker",
    copy: "svguse:/svg-icons/ft-icons.svg#copy",
    crown: "svguse:/svg-icons/ft-icons.svg#crown",
    dash: "svguse:/svg-icons/ft-icons.svg#dash",
    "dashed-outline": "svguse:/svg-icons/ft-icons.svg#dashed-outline",
    download: "svguse:/svg-icons/ft-icons.svg#download",
    drag: "svguse:/svg-icons/ft-icons.svg#drag",
    drink: "svguse:/svg-icons/ft-icons.svg#drink",
    error: "svguse:/svg-icons/ft-icons.svg#error",
    euro: "svguse:/svg-icons/ft-icons.svg#euro",
    "external-link": "svguse:/svg-icons/ft-icons.svg#external-link",
    "eye-off": "svguse:/svg-icons/ft-icons.svg#eye-off",
    "eye-open": "svguse:/svg-icons/ft-icons.svg#eye-open",
    fill: "svguse:/svg-icons/ft-icons.svg#fill",
    filter: "svguse:/svg-icons/ft-icons.svg#filter",
    fire: "svguse:/svg-icons/ft-icons.svg#fire",
    format_bold: "svguse:/svg-icons/ft-icons.svg#bold",
    format_italic: "svguse:/svg-icons/ft-icons.svg#italic",
    format_underlined: "svguse:/svg-icons/ft-icons.svg#underline",
    "full-screen": "svguse:/svg-icons/ft-icons.svg#full-screen",
    gradient: "svguse:/svg-icons/ft-icons.svg#spectrum",
    grid: "svguse:/svg-icons/ft-icons.svg#grid",
    home: "svguse:/svg-icons/ft-icons.svg#home",
    import: "svguse:/svg-icons/ft-icons.svg#import",
    info: "svguse:/svg-icons/ft-icons.svg#info",
    key: "svguse:/svg-icons/ft-icons.svg#key",
    "line-chart": "svguse:/svg-icons/ft-icons.svg#line-chart",
    link: "svguse:/svg-icons/ft-icons.svg#link",
    list: "svguse:/svg-icons/ft-icons.svg#list",
    logout: "svguse:/svg-icons/ft-icons.svg#logout",
    menu: "svguse:/svg-icons/ft-icons.svg#menu",
    moon: "svguse:/svg-icons/ft-icons.svg#moon",
    more: "svguse:/svg-icons/ft-icons.svg#more",
    pdf: "svguse:/svg-icons/ft-icons.svg#pdf",
    pencil: "svguse:/svg-icons/ft-icons.svg#pencil",
    plus: "svguse:/svg-icons/ft-icons.svg#plus",
    "qr-code": "svguse:/svg-icons/ft-icons.svg#qr-code",
    redo: "svguse:/svg-icons/ft-icons.svg#redo",
    save: "svguse:/svg-icons/ft-icons.svg#save",
    search: "svguse:/svg-icons/ft-icons.svg#search",
    selector: "svguse:/svg-icons/ft-icons.svg#selector",
    "send-backward": "svguse:/svg-icons/ft-icons.svg#send-backward",
    stack: "svguse:/svg-icons/ft-icons.svg#stack",
    "status-offline": "svguse:/svg-icons/ft-icons.svg#status-offline",
    "status-online": "svguse:/svg-icons/ft-icons.svg#status-online",
    style: "svguse:/svg-icons/ft-icons.svg#style",
    sun: "svguse:/svg-icons/ft-icons.svg#sun",
    transfer: "svguse:/svg-icons/ft-icons.svg#transfer",
    trash: "svguse:/svg-icons/ft-icons.svg#trash",
    tune: "svguse:/svg-icons/ft-icons.svg#tune",
    undo: "svguse:/svg-icons/ft-icons.svg#undo",
    unlink: "svguse:/svg-icons/ft-icons.svg#unlink",
    "user-circle": "svguse:/svg-icons/ft-icons.svg#user-circle",
    users: "svguse:/svg-icons/ft-icons.svg#users",
    "users-list": "svguse:/svg-icons/ft-icons.svg#users-list",
};

export function getDarkMode(): boolean {
    return (
        LocalStorage.getItem("FTDarkMode") ??
        globalThis.matchMedia("(prefers-color-scheme: dark)").matches
    );
}
